<?php
require_once __DIR__.'/Guard.php';ml_guard_shield(__FILE__);if(!function_exists('mlinst_root')){function mlinst_root(){return rtrim(str_replace('\\','/',dirname(__DIR__)),'/');}}if(!function_exists('mlinst_rand_token')){function mlinst_rand_token(){if(function_exists('openssl_random_pseudo_bytes')){$a=false;$c=@openssl_random_pseudo_bytes(16,$a);if($c!==false&&strlen($c)>=16){return substr(bin2hex($c),0,16);}}return substr(md5(uniqid('ml',true).mt_rand(100000,999999)),0,16);}}if(!function_exists('mlinst_rand_pass')){function mlinst_rand_pass($a=16){$b='abcdefghjkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789';$c=strlen($b)-1;$d='';for($e=0;$e<$a;$e++){$d.=$b[mt_rand(0,$c)];}return $d;}}if(!function_exists('mlinst_q')){function mlinst_q($a){return"'".str_replace(array('\\',"'"),array('\\\\',"\\'"),(string)$a)."'";}}if(!function_exists('mlinst_eq')){function mlinst_eq($b,$a){$b=(string)$b;$a=(string)$a;if(strlen($b)!==strlen($a)){return false;}$c=0;for($d=0,$e=strlen($b);$d<$e;$d++){$c|=ord($b[$d])^ord($a[$d]);}return $c===0;}}if(!function_exists('mlinst_tables')){function mlinst_tables(){return array("CREATE TABLE IF NOT EXISTS media_items (
  id            INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  source        VARCHAR(32)  NOT NULL DEFAULT '',
  source_id     VARCHAR(64)  NOT NULL DEFAULT '',
  type          VARCHAR(32)  NOT NULL DEFAULT '',
  title         VARCHAR(512) NOT NULL DEFAULT '',
  original_title VARCHAR(512) NOT NULL DEFAULT '',
  year          SMALLINT     DEFAULT NULL,
  rating        DECIMAL(6,2) DEFAULT NULL,
  vote_count    INT          DEFAULT NULL,
  api_calls     INT UNSIGNED NOT NULL DEFAULT 0,
  clicks        INT UNSIGNED NOT NULL DEFAULT 0,
  genres        TEXT,
  poster        VARCHAR(1024) NOT NULL DEFAULT '',
  backdrop      VARCHAR(1024) NOT NULL DEFAULT '',
  overview      TEXT,
  download_url  MEDIUMTEXT   NULL,
  extra         TEXT,
  payload       MEDIUMTEXT,
  cached_at     DATETIME     DEFAULT NULL,
  refresh_at    DATETIME     DEFAULT NULL,
  updated_at    DATETIME     DEFAULT NULL,
  UNIQUE KEY uq_src (source, source_id, type),
  KEY idx_type (type),
  KEY idx_title (title(191)),
  KEY idx_year (year),
  KEY idx_rating (rating)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4","CREATE TABLE IF NOT EXISTS sync_log (
  id         INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  task       VARCHAR(64) NOT NULL DEFAULT '',
  detail     TEXT,
  items      INT DEFAULT 0,
  created_at DATETIME DEFAULT NULL,
  KEY idx_task (task)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4","CREATE TABLE IF NOT EXISTS link_checks (
  id         INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  item_id    INT UNSIGNED NOT NULL,
  label      VARCHAR(64)  NOT NULL DEFAULT '',
  url        VARCHAR(2048) NOT NULL DEFAULT '',
  status     TINYINT NOT NULL DEFAULT 0,
  http_code  SMALLINT NOT NULL DEFAULT 0,
  checked_at DATETIME DEFAULT NULL,
  KEY idx_item (item_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4","CREATE TABLE IF NOT EXISTS app_settings (
  `k`          VARCHAR(64) NOT NULL,
  `v`          TEXT,
  `updated_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`k`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4","CREATE TABLE IF NOT EXISTS `app_users` (
  `id`         INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username`   VARCHAR(128) NOT NULL DEFAULT '',
  `email`      VARCHAR(128) NOT NULL DEFAULT '',
  `pass_hash`  VARCHAR(255) NOT NULL DEFAULT '',
  `status`     TINYINT      NOT NULL DEFAULT 1 COMMENT '1=正常 0=禁用 2=待审核',
  `ip`         VARCHAR(64)  NOT NULL DEFAULT '',
  `ua`         VARCHAR(255) NOT NULL DEFAULT '',
  `req_count`  INT UNSIGNED NOT NULL DEFAULT 0,
  `fail_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `lock_until` DATETIME     DEFAULT NULL,
  `created_at` DATETIME     DEFAULT NULL,
  `last_login` DATETIME     DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_username` (`username`),
  KEY `idx_email` (`email`),
  KEY `idx_status` (`status`),
  KEY `idx_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='前台注册用户'","CREATE TABLE IF NOT EXISTS `app_requests` (
  `id`         INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id`    INT UNSIGNED NOT NULL DEFAULT 0,
  `username`   VARCHAR(64)  NOT NULL DEFAULT '',
  `title`      VARCHAR(255) NOT NULL DEFAULT '',
  `type`       VARCHAR(32)  NOT NULL DEFAULT '',
  `year`       SMALLINT     DEFAULT NULL,
  `note`       TEXT,
  `contact`    VARCHAR(128) NOT NULL DEFAULT '',
  `status`     VARCHAR(16)  NOT NULL DEFAULT 'pending',
  `admin_note` TEXT,
  `item_id`    INT UNSIGNED NOT NULL DEFAULT 0,
  `ip`         VARCHAR(64)  NOT NULL DEFAULT '',
  `created_at` DATETIME     DEFAULT NULL,
  `updated_at` DATETIME     DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_user` (`user_id`),
  KEY `idx_status` (`status`),
  KEY `idx_created` (`created_at`),
  KEY `idx_title` (`title`(191))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资源请求'","CREATE TABLE IF NOT EXISTS `app_api_tokens` (
  `id`           INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name`         VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '令牌名称/用途说明',
  `token`        VARCHAR(128) NOT NULL DEFAULT '' COMMENT '令牌值',
  `user_id`      INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '关联注册用户，0=未关联',
  `status`       TINYINT      NOT NULL DEFAULT 1 COMMENT '1=启用 0=禁用',
  `daily_limit`  INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '每日调用上限，0=不限',
  `ip_whitelist` TEXT COMMENT 'IP 白名单，逗号分隔，留空=不限',
  `usage_count`  INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '累计调用次数',
  `last_used`    DATETIME     DEFAULT NULL COMMENT '最后调用时间',
  `created_at`   DATETIME     DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_token` (`token`),
  KEY `idx_user` (`user_id`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='API 调用令牌'","CREATE TABLE IF NOT EXISTS `app_api_logs` (
  `id`            BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `token_id`      INT UNSIGNED  NOT NULL DEFAULT 0,
  `token_name`    VARCHAR(64)   NOT NULL DEFAULT '',
  `endpoint`      VARCHAR(128)  NOT NULL DEFAULT '',
  `method`        VARCHAR(10)   NOT NULL DEFAULT 'GET',
  `params`        TEXT,
  `ip`            VARCHAR(64)   NOT NULL DEFAULT '',
  `ua`            VARCHAR(255)  NOT NULL DEFAULT '',
  `response_code` SMALLINT      NOT NULL DEFAULT 200,
  `cost_ms`       INT UNSIGNED  NOT NULL DEFAULT 0,
  `created_at`    DATETIME      DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_token` (`token_id`),
  KEY `idx_endpoint` (`endpoint`),
  KEY `idx_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='API 调用日志'",);}}if(!function_exists('mlinst_default_adapters')){function mlinst_default_adapters(){}}if(!function_exists('mlinst_default_pan')){function mlinst_default_pan(){return array('夸克','迅雷','光鸭','百度','UC');}}if(!function_exists('mlinst_config_content')){function mlinst_config_content($a,$b,$c='',$d=[]){$e="\n    ";$f="<?php\n";$f.="/**\n * 媒资资料库 API - 配置文件（由安装器自动生成 ".date('Y-m-d H:i:s')."）\n";$f.=" * 如需改动数据库/密钥，直接改本文件即可；也可在后台「系统设置」里改（优先级更高）。\n */\n\n";$f.="/* 安全守卫：本文件只应被入口（index.php / check.php / cron）引入；\n";$f.="   直接被网址请求时返回 404 —— 见 core/Guard.php。 */\n";$f.="if (is_file(__DIR__ . '/../core/Guard.php')) {\n";$f.="    require_once __DIR__ . '/../core/Guard.php';\n";$f.="    if (function_exists('ml_guard_shield')) { ml_guard_shield(__FILE__); }\n";$f.="}\n\n";$f.="return [\n";$f.=$e."// 数据库（宝塔新建的 MySQL 库）\n";$f.=$e."'db' => [\n";$f.=$e."    'host'     => ".mlinst_q($a['host']).",\n";$f.=$e."    'port'     => ".(int)$a['port'].",\n";$f.=$e."    'dbname'   => ".mlinst_q($a['dbname']).",\n";$f.=$e."    'user'     => ".mlinst_q($a['user']).",\n";$f.=$e."    'pass'     => ".mlinst_q($a['pass']).",\n";$f.=$e."    'charset'  => 'utf8mb4',\n";$f.=$e."],\n\n";$f.=$e."// TMDB（影视/人物） https://www.themoviedb.org/settings/api 申请\n";$f.=$e."'tmdb' => [\n";$f.=$e."    'api_key'   => ".mlinst_q($b).",\n";$f.=$e."    'base'      => 'https://api.themoviedb.org/3',\n";$f.=$e."    'image_base'=> 'https://image.tmdb.org/t/p/',\n";$f.=$e."    'lang'      => 'zh-CN',\n";$f.=$e."],\n\n";$f.=$e."// 红果短剧（国产短剧） https://orz.icicic.icu\n";$f.=$e."'hongguoduanju' => [\n";$f.=$e."    'base'      => 'https://orz.icicic.icu/api/api.php',\n";$f.=$e."],\n\n";$f.=$e."// 启用的数据源适配器\n";$f.=$e."'adapters' => [".(isset($d[0])&&$d[0]!==''?mlinst_q($d[0]):'').(isset($d[1])&&$d[1]!==''?", ".mlinst_q($d[1]):'').(isset($d[2])&&$d[2]!==''?", ".mlinst_q($d[2]):'')."],\n\n";$f.=$e."// 缓存策略\n";$f.=$e."'cache' => [\n";$f.=$e."    'ttl_days'   => 7,\n";$f.=$e."    'stale_days' => 30,\n";$f.=$e."],\n\n";$f.=$e."// TMDB 兼容代理是否强制校验 key（默认 false，ZBLOK 改 base URL 即用）\n";$f.=$e."'proxy' => [\n";$f.=$e."    'require_key' => false,\n";$f.=$e."    'proxy_key'   => '',\n";$f.=$e."],\n\n";$f.=$e."// 后台目录与显示（★ v1.7.0 起后台用账号+密码登录，不再有 admin.token）\n";$f.=$e."'admin' => [\n";$f.=$e."    'dir'       => 'admin',   // 后台目录名（必须以 admin 结尾）\n";$f.=$e."    'show_link' => 1,           // 1=主页显示管理后台按钮；0=隐藏\n";$f.=$e."    'show_icon' => 1,           // 1=按钮带图标；0=纯文字\n";$f.=$e."],\n\n";$f.=$e."// ================= 站点设置（v1.6.0 起；建议都到后台「站点设置」里改） =================\n";$f.=$e."'site' => [\n";$f.=$e."    'name'      => '媒资资料库', 'name_hide' => 0, 'slogan' => '',\n";$f.=$e."    'logo'      => '', 'favicon' => '', 'url' => '',\n";$f.=$e."    'footer_intro' => '', 'declare' => '', 'copyright' => '',\n";$f.=$e."],\n\n";$f.=$e."// SEO：首页三件套 + 标题模板 + 统计代码 + robots / sitemap\n";$f.=$e."'seo' => [\n";$f.=$e."    'title' => '', 'keywords' => '', 'description' => '', 'stats_code' => '',\n";$f.=$e."    'pattern_type' => '{type} - 第{page}页 - {site}',\n";$f.=$e."    'pattern_item' => '{title}({year}) - {type} - {site}',\n";$f.=$e."    'item_desc_len' => 0, 'robots' => '', 'sitemap' => 1, 'sitemap_size' => 5000,\n";$f.=$e."],\n\n";$f.=$e."// 跳转与扫码 + 前台模板（target 与 qr 都为空 = 不拦截访客）\n";$f.=$e."'redirect' => [\n";$f.=$e."    'mode' => 'jump_scan', 'target' => '', 'mobile' => 0, 'qr' => '', 'qr_tip' => '',\n";$f.=$e."    'tpl' => 'classic', 'simple_mode' => 'auto', 'nav_show' => 'home,latest',\n";$f.=$e."    'nav_external' => '', 'rank_style' => 'grid', 'latest' => 1,\n";$f.=$e."],\n\n";$f.=$e."// 网盘账号（后台「站点设置 → 网盘链接」；只保存与检测，不会登录你的网盘）\n";$f.=$e."'pan' => [\n";$f.=$e."    'group' => 'quark,aliyun,baidu,uc,xunlei,guangya',\n";$f.=$e."    // 'quark_cookie' => '', 'quark_dir' => '', 'quark_tmp' => '',  // 其余同理\n";$f.=$e."],\n\n";$f.=$e."// 接口配置：PanSou 网盘搜索（采集后自动补网盘下载地址）\n";$f.=$e."'pansou' => [\n";$f.=$e."    'enable' => 0, 'mode' => 'local', 'url' => 'http://127.0.0.1:8888',\n";$f.=$e."    'user' => '', 'pass' => '', 'line' => 'PanSou 主线路', 'types' => '',\n";$f.=$e."    'auto' => 1, 'policy' => 'exact', 'match' => 80, 'max' => 5,\n";$f.=$e."    'delay' => 1000, 'ttl' => 720,\n";$f.=$e."],\n\n";$f.=$e."// 资源请求（注册 + 求片区）；两张表由程序首次使用时自动创建\n";$f.=$e."'req' => [\n";$f.=$e."    'open' => 1, 'logon' => 1, 'audit' => 0, 'verify' => 1,\n";$f.=$e."    'guest_view' => 1, 'public' => 1, 'contact' => 1, 'nav' => 1,\n";$f.=$e."    'daily' => 5, 'mintitle' => 2,\n";$f.=$e."    'page_title' => '资源请求', 'page_intro' => '', 'notice' => '',\n";$f.=$e."],\n";$f.="];\n";return $f;}}if(!function_exists('mlinst_pan_content')){function mlinst_pan_content($a){$b=array();foreach($a as $c){$b[]="    '".str_replace(array('\\',"'"),array('\\\\',"\\'"),$c)."',";}return"<?php\n/**\n * 网盘类型（后台「下载链接」下拉用）\n * 新增网盘只改本文件即可；升级包覆盖本文件也不会影响数据库与密钥配置。\n */\n\n"."/* 安全守卫：本文件只应被入口引入；直接被网址请求时返回 404 —— 见 core/Guard.php。 */\n"."if (is_file(__DIR__ . '/../core/Guard.php')) {\n"."    require_once __DIR__ . '/../core/Guard.php';\n"."    if (function_exists('ml_guard_shield')) { ml_guard_shield(__FILE__); }\n"."}\n\n"."return [\n".implode("\n",$b)."\n];\n";}}if(!function_exists('mlinst_write')){function mlinst_write($a,$b){$c=dirname($a);if(!is_dir($c)){@mkdir($c,0755,true);}if(file_exists($a)){@copy($a,$a.'.bak-'.date('Ymd-His'));}return@file_put_contents($a,$b)!==false;}}if(!function_exists('mlinst_env_check')){function mlinst_env_check($a){$a=rtrim(str_replace('\\','/',$a),'/');$b=array();$c=version_compare(PHP_VERSION,'5.6.0','>=');$b[]=array('label'=>'PHP 版本 ≥ 5.6','ok'=>$c,'level'=>$c?'ok':'fail','detail'=>'当前 '.PHP_VERSION.'（'.php_sapi_name().'）','fix'=>$c?'':'宝塔 → 网站 → 设置 → PHP 版本，选 7.4 / 8.0 等；本程序支持 5.6 ~ 8.2',);foreach(array('pdo_mysql'=>'数据库访问必需','curl'=>'采集上游数据必需','json'=>'接口与配置读写必需')as $d=>$e){$f=extension_loaded($d);$b[]=array('label'=>'扩展 '.$d,'ok'=>$f,'level'=>$f?'ok':'fail','detail'=>$f?$e:('缺少（'.$e.'）'),'fix'=>$f?'':'宝塔 → 网站 → 设置 → PHP → 安装扩展，勾选 '.$d.' 后重试',);}$g=extension_loaded('mbstring');$b[]=array('label'=>'扩展 mbstring','ok'=>true,'level'=>$g?'ok':'warn','detail'=>$g?'已启用（中文标题截断更准确）':'未启用（不影响运行，建议装上）','fix'=>$g?'':'宝塔 → PHP → 安装扩展 → mbstring',);$h=extension_loaded('openssl');$b[]=array('label'=>'扩展 openssl','ok'=>true,'level'=>$h?'ok':'warn','detail'=>$h?'已启用（令牌随机性更好）':'未启用（会用 md5+mt_rand 兜底，仍可用）','fix'=>'',);$i=$a.'/config';if(!is_dir($i)){@mkdir($i,0755,true);}$j=is_dir($i)&&is_writable($i);$b[]=array('label'=>'config/ 目录可写','ok'=>$j,'level'=>$j?'ok':'fail','detail'=>$j?'可写（安装器要在这里生成 config.php 与 install.lock）':'不可写：'.$i,'fix'=>$j?'':'宝塔 → 网站 → 设置 → 网站目录 → 权限，给站点目录 755、属主 www',);$k=is_writable($a);$b[]=array('label'=>'站点根目录可写','ok'=>true,'level'=>$k?'ok':'warn','detail'=>$k?'可写':'不可写（安装仍可完成；只是 uisc/ 需手动创建）','fix'=>$k?'':'宝塔 → 网站目录权限给 www 属主；或手动创建 uisc/ 目录',);$l=is_dir($a.'/uisc');if(!$l&&$k){@mkdir($a.'/uisc',0755,true);$l=is_dir($a.'/uisc');}$b[]=array('label'=>'uisc/ 静态页目录','ok'=>true,'level'=>$l?'ok':'warn','detail'=>$l?'已就绪（内页静态化输出目录）':'尚未创建（后台「重建静态页」时自动建）','fix'=>'',);return $b;}}if(!function_exists('mlinst_env_ok')){function mlinst_env_ok($a){foreach($a as $b){if(!empty($b['level'])&&$b['level']==='fail'){return false;}}return true;}}if(!function_exists('mlinst_normalize')){function mlinst_normalize($a){$b=function($b,$c='')use($a){return isset($a[$b])&&is_scalar($a[$b])?trim((string)$a[$b]):$c;};$c=$b('host','127.0.0.1');if($c===''){$c='127.0.0.1';}$d=(int)$b('port','3306');if($d<1||$d>65535){$d=3306;}$e=array();if(isset($a['adapters'])&&is_array($a['adapters'])){foreach($a['adapters']as $f){$f=strtolower(trim((string)$f));if(in_array($f,array('tmdb','hongguoduanju'),true)){$e[]=$f;}}}if(empty($e)){$e=mlinst_default_adapters();}return array('host'=>$c,'port'=>$d,'dbname'=>$b('dbname'),'user'=>$b('user'),'pass'=>isset($a['pass'])?(string)$a['pass']:'','admin_user'=>$b('admin_user'),'admin_pass'=>isset($a['admin_pass'])?(string)$a['admin_pass']:'','admin_pass2'=>isset($a['admin_pass2'])?(string)$a['admin_pass2']:'','tmdb'=>$b('tmdb'),'site_url'=>rtrim($b('site_url'),'/'),'site_name'=>$b('site_name','媒资资料库'),'adapters'=>$e,);}}if(!function_exists('mlinst_validate')){function mlinst_validate($a){if($a['dbname']===''){return'数据库名不能为空（宝塔 → 数据库 → 新建时那个库名）。';}if($a['user']===''){return'数据库用户名不能为空。';}$b=$a['admin_user'];if($b===''){return'请填写管理员账号（推荐用邮箱，登录后台用）。';}if(strpos($b,'@')!==false){if(strlen($b)>128||!filter_var($b,FILTER_VALIDATE_EMAIL)){return'管理员账号邮箱格式不正确，请检查（示例：admin@example.com）。';}}elseif(!preg_match('/^[A-Za-z0-9_.-]{3,32}$/',$b)){return'管理员账号只能包含字母、数字、下划线、点、短横线，长度 3~32 位；或直接填邮箱。';}if(strlen($a['admin_pass'])<6){return'管理员密码至少 6 位。';}if($a['admin_pass']!==$a['admin_pass2']){return'两次输入的管理员密码不一致。';}return'';}}if(!function_exists('mlinst_connect')){function mlinst_connect($a){$b='mysql:host='.$a['host'].';port='.(int)$a['port'].';dbname='.$a['dbname'].';charset=utf8mb4';return new PDO($b,$a['user'],$a['pass'],array(PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_TIMEOUT=>6,));}}if(!function_exists('mlinst_dsn_tip')){function mlinst_dsn_tip(){return array('数据库名 / 用户名 / 密码写错（宝塔 → 数据库 里可改密码）','数据库还没建（先在宝塔 → 数据库里新建一个）','MySQL 8 + PHP 5.6 的 caching_sha2_password 认证不兼容：在宝塔 → 数据库 → 该库用户 → 改密码时选 mysql_native_password','数据库地址不对（宝塔本机一般填 127.0.0.1；用了独立数据库服务器就填它的 IP）',);}}if(!function_exists('mlinst_install')){function mlinst_install($a,$b){$a=rtrim(str_replace('\\','/',$a),'/');$c=array();$d=array('ok'=>false,'error'=>'','steps'=>array(),'admin_user'=>'','mysql'=>'','files'=>array(),'config_file'=>$a.'/config/config.php','lock_file'=>$a.'/config/install.lock',);$e=mlinst_normalize($b);$f=ml_install_state($a);if(!empty($f['installed'])){$d['error']='本站已安装（'.$f['reason'].'）。要重装请先删除 config/install.lock 与 config/config.php。';$c[]=array('label'=>'安装状态检查','ok'=>false,'detail'=>$d['error']);$d['steps']=$c;return $d;}$c[]=array('label'=>'安装状态检查','ok'=>true,'detail'=>'尚未安装，可以继续（'.$f['reason'].'）');$g=mlinst_env_check($a);if(!mlinst_env_ok($g)){$h=array();foreach($g as $i){if($i['level']==='fail'){$h[]=$i['label'];}}$d['error']='环境不满足：'.implode('、',$h);$c[]=array('label'=>'环境自检','ok'=>false,'detail'=>$d['error']);$d['steps']=$c;return $d;}$c[]=array('label'=>'环境自检','ok'=>true,'detail'=>'PHP '.PHP_VERSION.'，必需扩展齐全，config/ 可写');$j=mlinst_validate($e);if($j!==''){$d['error']=$j;$c[]=array('label'=>'参数校验','ok'=>false,'detail'=>$j);$d['steps']=$c;return $d;}if($e['site_name']===''){$e['site_name']='媒资资料库';}$d['admin_user']=$e['admin_user'];$c[]=array('label'=>'参数校验','ok'=>true,'detail'=>'数据库 '.$e['user'].'@'.$e['host'].':'.$e['port'].'/'.$e['dbname']);try{$k=mlinst_connect($e);}catch(Exception $l){$d['error']='数据库连接失败：'.$l->getMessage();$c[]=array('label'=>'连接数据库','ok'=>false,'detail'=>$d['error']);$d['steps']=$c;return $d;}$m='';try{$m=(string)$k->query('SELECT VERSION()')->fetchColumn();}catch(Exception $l){$m='';}$d['mysql']=$m;$c[]=array('label'=>'连接数据库','ok'=>true,'detail'=>'连接成功'.($m!==''?'，MySQL '.$m:''));try{foreach(mlinst_tables()as $n){$k->exec($n);}}catch(Exception $l){$d['error']='建表失败：'.$l->getMessage();$c[]=array('label'=>'创建数据表','ok'=>false,'detail'=>$d['error']);$d['steps']=$c;return $d;}$c[]=array('label'=>'创建数据表','ok'=>true,'detail'=>'media_items / sync_log / link_checks / app_settings / app_users / app_requests / app_api_tokens / app_api_logs');try{$o=password_hash($e['admin_pass'],PASSWORD_DEFAULT);if($o===false||$o===null){$o='$sha256$'.hash('sha256','ml-admin|'.$e['admin_pass']);}$p=date('Y-m-d H:i:s');$q=(strpos($e['admin_user'],'@')!==false)?$e['admin_user']:'ml-admin@local';$r=$k->prepare('SELECT id FROM `app_users` WHERE username=? LIMIT 1');$r->execute(array($e['admin_user']));if($r->fetchColumn()){$s=$k->prepare('UPDATE `app_users` SET pass_hash=?, last_login=? WHERE username=?');$s->execute(array($o,$p,$e['admin_user']));$c[]=array('label'=>'创建管理员账号','ok'=>true,'detail'=>'账号「'.$e['admin_user'].'」已存在，密码已更新（这是后台管理员，请记牢密码）');}else{$s=$k->prepare('INSERT INTO `app_users` (`username`,`email`,`pass_hash`,`status`,`created_at`,`last_login`)
                     VALUES (:u, :e, :p, 1, :c, :c)');$s->execute(array(':u'=>$e['admin_user'],':e'=>$q,':p'=>$o,':c'=>$p,));$c[]=array('label'=>'创建管理员账号','ok'=>true,'detail'=>'账号「'.$e['admin_user'].'」已创建（这是后台管理员，请记牢密码）');}}catch(Exception $l){$d['error']='创建管理员账号失败：'.$l->getMessage();$c[]=array('label'=>'创建管理员账号','ok'=>false,'detail'=>$d['error']);$d['steps']=$c;return $d;}$t=array('host'=>$e['host'],'port'=>(int)$e['port'],'dbname'=>$e['dbname'],'user'=>$e['user'],'pass'=>$e['pass'],);$u='';$v=mlinst_config_content($t,$u);if($e['site_name']!==''||$e['site_url']!==''){$v=str_replace("'name'      => '媒资资料库', 'name_hide' => 0, 'slogan' => '',","'name'      => ".mlinst_q($e['site_name']).", 'name_hide' => 0, 'slogan' => '',",$v);if($e['site_url']!==''){$v=str_replace("'logo'      => '', 'favicon' => '', 'url' => '',","'logo'      => '', 'favicon' => '', 'url' => ".mlinst_q($e['site_url']).",",$v);}}if(!mlinst_write($d['config_file'],$v)){$d['error']='写入 config/config.php 失败（目录权限不足）';$c[]=array('label'=>'生成 config/config.php','ok'=>false,'detail'=>$d['error']);$d['steps']=$c;return $d;}$w=(string)@file_get_contents($d['config_file']);if(strpos($w,'<?php')!==0||strpos($w,"'dbname'")===false){$d['error']='config/config.php 内容异常（可能磁盘已满或被安全软件改写）';$c[]=array('label'=>'生成 config/config.php','ok'=>false,'detail'=>$d['error']);$d['steps']=$c;return $d;}$d['files'][]='config/config.php';$c[]=array('label'=>'生成 config/config.php','ok'=>true,'detail'=>'已写入数据库配置');$x=$a.'/config/pan_types.php';if(!file_exists($x)){if(mlinst_write($x,mlinst_pan_content(mlinst_default_pan()))){$d['files'][]='config/pan_types.php';$c[]=array('label'=>'生成 config/pan_types.php','ok'=>true,'detail'=>'默认：'.implode(' / ',mlinst_default_pan()));}else{$c[]=array('label'=>'生成 config/pan_types.php','ok'=>true,'detail'=>'写入失败，但后台内置了一样的默认值，不影响使用');}}else{$c[]=array('label'=>'生成 config/pan_types.php','ok'=>true,'detail'=>'已存在，保持不变');}$y="installed at ".date('c')."\n"."via ".(php_sapi_name()==='cli'?'tools/install-cli.php':'install.php (web)')."\n"."version ".(defined('ML_APP_VERSION')?ML_APP_VERSION:'')."\n";if(@file_put_contents($d['lock_file'],$y)===false){$d['error']='写入 config/install.lock 失败：安装器无法自动失效，请手动创建该文件（内容随意）';$c[]=array('label'=>'写入安装锁 install.lock','ok'=>false,'detail'=>$d['error']);$d['steps']=$c;return $d;}$d['files'][]='config/install.lock';$c[]=array('label'=>'写入安装锁 install.lock','ok'=>true,'detail'=>'已锁定：install.php 从此对所有人返回 404');$z="安装时间: ".date('Y-m-d H:i:s')."\n"."站点目录: ".$a."\n"."数据库  : ".$e['user'].'@'.$e['host'].':'.$e['port'].'/'.$e['dbname']."\n"."管理员账号: ".$e['admin_user']."\n"."后台地址  : 站点网址 + /".(defined('ML_APP_VERSION')?'':'')."admin\n"."※ 密码不写在这里。本文件含账号信息，记下后可直接删除；放在 config/ 下公网访问不到。\n";if(@file_put_contents($a.'/config/install-info.txt',$z)!==false){$d['files'][]='config/install-info.txt';}if($e['site_url']!==''){$c[]=array('label'=>'站点信息','ok'=>true,'detail'=>'站点名「'.$e['site_name'].'」，网址 '.$e['site_url']);}$d['ok']=true;$d['steps']=$c;return $d;}}